name: build image

on:
  push:
    tags:
      - "**"

jobs:
  build-and-publish-latest:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/build-push-action@v6
      with:
        push: true
        tags: ghcr.io/alantang888/getssl_with_lexicon:${{ github.ref_name }},ghcr.io/alantang888/getssl_with_lexicon:latest
        platforms: linux/amd64,linux/arm64
